package godborm

import (
	"bytes"
	"fmt"
	"go-db-orm/godborm/client"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

// GenerateModels reads schema files and writes Go structs to outPath.
// schemaPath: folder containing .godb files.
// packageName: package name for generated structs.
// outPath: target .go file path.
func GenerateModels(schemaPath, packageName, outPath string) error {
	files, err := os.ReadDir(schemaPath)
	if err != nil {
		return fmt.Errorf("cannot read schema folder: %w", err)
	}

	var models []Model
	for _, file := range files {
		if !isSchemaFile(file.Name()) {
			continue
		}
		filePath := filepath.Join(schemaPath, file.Name())
		fileModels, err := parseSchemaFile(filePath)
		if err != nil {
			return err
		}
		models = append(models, fileModels...)
	}

	src, err := renderModels(packageName, models)
	if err != nil {
		return err
	}

	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		return fmt.Errorf("failed to write generated file: %w", err)
	}
	return nil
}

func renderModels(packageName string, models []Model) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by godborm. DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	needsTime := false
	for _, m := range models {
		for _, f := range m.Fields {
			if strings.Contains(mapTypeToGo(f), "time.Time") {
				needsTime = true
				break
			}
		}
	}
	if needsTime {
		buf.WriteString("import \"time\"\n\n")
	}

	for _, m := range models {
		buf.WriteString(fmt.Sprintf("type %s struct {\n", exportName(m.Name)))
		for _, f := range m.Fields {
			goType := mapTypeToGo(f)
			colName := client.ToSnakeCase(f.Name)
			
			isRelation := f.IsRelation()
			
			tagParts := []string{}

			if !isRelation {
				tagParts = append(tagParts, fmt.Sprintf("db:\"%s\"", colName))
			}
			tagParts = append(tagParts, fmt.Sprintf("json:\"%s,omitempty\"", colName))
			
			godbTag := ""
			if f.IsID {
				godbTag = "primary_key"
				if f.DefaultValue != "" {
					godbTag += "," + strings.TrimSuffix(f.DefaultValue, "()")
				}
			} else if isRelation {
				godbTag = "relation"
				if f.Relation != nil {
					if len(f.Relation.Fields) > 0 {
						godbTag += ",fields=" + strings.Join(f.Relation.Fields, ":")
					}
					if len(f.Relation.References) > 0 {
						godbTag += ",references=" + strings.Join(f.Relation.References, ":")
					}
				}
			}

			if godbTag != "" {
				tagParts = append(tagParts, fmt.Sprintf("godb:\"%s\"", godbTag))
			}


			tag := fmt.Sprintf("`%s`", strings.Join(tagParts, " "))
			buf.WriteString(fmt.Sprintf("\t%s %s %s\n", exportName(f.Name), goType, tag))
		}

		buf.WriteString("}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted source to help debugging if format fails.
		return buf.Bytes(), fmt.Errorf("failed to format generated source: %w", err)
	}
	return formatted, nil
}
